apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: bgd
  name: bgd
  namespace: test
spec:
  ports:
  - port: 8050
    protocol: TCP
    targetPort: 8050
  selector:
    app: bgd